konnect_pat             = "kpat_sHc8xEXS5F9uk1v8rnE6Np1zXryg8arPagdG9FufNkfO9el7A"
konnect_server_url      = "https://us.api.konghq.com"
control_plane_name      = "Test Control Plane Name"
control_plane_description = "Example control plane for Terraform configuration"
portal_id               = "1edcaab3-b841-4332-a1f2-1100f88c2716"